# -*- coding: utf-8 -*-
"""Second content pass (batch 2a) — theory expansion for lessons 1–4.

Theory-only override keyed by lesson number; exercises untouched. Classic textbook
presentation (numbered points, contrastive examples, translated illustrations, a closing
mini-dialogue). All wording and examples original.
"""

THEORY_EXPAND_2A = {
    1: (
        'В испанском алфавите 27 букв: 26 латинских плюс особая ñ. Орфография почти '
        'фонетична: слово читается так, как пишется, по небольшому набору правил.\n\n'
        '1. ГЛАСНЫЕ. Их пять: a, e, i, o, u. Произносятся чётко и кратко, без редукции: '
        'безударное o никогда не превращается в «а» (как в русском «молоко»). Гласные '
        'делятся на сильные (a, e, o) и слабые (i, u). Сочетание сильного и слабого '
        'образует ДИФТОНГ и читается как один слог: bien (хорошо), aire (воздух), ciudad '
        '(город), bueno (хороший). Две сильные гласные читаются раздельно, по слогам: '
        'le-er (читать), ma-es-tro (учитель).\n\n'
        '2. СОГЛАСНЫЕ И ОСОБЫЕ СОЧЕТАНИЯ:\n'
        '• ñ — мягкое «нь»: niño (ребёнок), España, mañana (утро/завтра);\n'
        '• ll — в современном языке «й»: llave (ключ), calle (улица), lluvia (дождь);\n'
        '• ch — «ч»: chico (мальчик), coche (машина), noche (ночь);\n'
        '• h — никогда не читается: hola → «ола», hotel → «отель», ahora → «аора»;\n'
        '• j — твёрдое гортанное «х»: jardín (сад), joven (молодой), trabajo (работа);\n'
        '• g перед e, i — тоже «х»: gente (люди), página; перед a, o, u — «г»: gato '
        '(кот). Чтобы получить «ге/ги», пишут немую u: guerra (война), guitarra;\n'
        '• c перед e, i — межзубное «с» в Испании (в Латинской Америке обычное «с»): cine '
        '(кино), cielo (небо); иначе — «к»: casa, cosa. Сочетание qu перед e, i даёт «к»: '
        'queso (сыр), aquí (здесь);\n'
        '• z — тот же звук, что c перед e/i: zapato (ботинок), plaza (площадь);\n'
        '• v произносится как b: vino звучит «бино»; разницы между b и v в речи нет;\n'
        '• r в начале слова и rr — раскатистое: rosa, perro (собака); одиночная r внутри '
        'слова — одноударная: pero (но).\n\n'
        '3. УДАРЕНИЕ. Два простых правила:\n'
        '• слово оканчивается на гласную, -n или -s → ударение на ПРЕДПОСЛЕДНЕМ слоге: '
        'CA-sa, HA-blan, LU-nes;\n'
        '• слово оканчивается на любую другую согласную → ударение на ПОСЛЕДНЕМ слоге: '
        'ha-BLAR, ciu-DAD, es-pa-ÑOL.\n'
        'Все исключения помечаются графическим ударением (tilde): café, árbol (дерево), '
        'canción (песня), teléfono. Тильда также различает одинаково пишущиеся слова: tú '
        '(ты) — tu (твой), sí (да) — si (если), qué (что?) — que (что/который).\n\n'
        '4. ПРАКТИЧЕСКИЙ СОВЕТ: читайте вслух с первого дня. Испанский вознаграждает '
        'проговаривание — почти нет «немых» букв (кроме h и u в gue/gui/que/qui), поэтому '
        'связь «буква — звук» закрепляется быстро.\n\n'
        '5. МИНИ-ДИАЛОГ (обратите внимание на звуки):\n'
        '— ¡Hola! ¿Cómo te llamas? (Привет! Как тебя зовут? — h немая, ll как «й».)\n'
        '— Me llamo Guille. ¿Y tú? (Меня зовут Гилье. А тебя? — gui даёт «ги».)\n'
        '— Jorge. Vivo aquí, en la calle Cervantes. (Хорхе. Живу здесь, на улице '
        'Сервантеса. — j и g перед e как «х», v как «б».)\n'
        '— ¡Mucho gusto! (Очень приятно!)'
    ),
    2: (
        'В испанском у существительных только два рода — мужской и женский; среднего '
        'рода нет. Род — постоянный признак слова: от него зависят артикль, '
        'прилагательное и местоимения, поэтому существительное учат ВМЕСТЕ с артиклем.\n\n'
        '1. ОСНОВНЫЕ ПРИЗНАКИ РОДА ПО ОКОНЧАНИЮ:\n'
        '• -o → как правило, мужской: el libro (книга), el vaso (стакан), el año (год);\n'
        '• -a → как правило, женский: la mesa (стол), la casa (дом), la ventana (окно);\n'
        '• -ción, -sión, -dad, -tad, -umbre → всегда женский: la canción (песня), la '
        'ciudad (город), la libertad (свобода), la costumbre (обычай);\n'
        '• -or, -aje → обычно мужской: el amor (любовь), el viaje (путешествие).\n\n'
        '2. ВАЖНЫЕ ИСКЛЮЧЕНИЯ, которые надо выучить: el día (день), el mapa (карта), el '
        'sofá (диван) — мужской при окончании -a; la mano (рука), la foto (фото), la moto '
        '(мотоцикл) — женский при окончании -o. Слова греческого происхождения на -ma — '
        'мужского рода: el problema, el idioma (язык), el tema, el sistema.\n\n'
        '3. ОДУШЕВЛЁННЫЕ существительные часто образуют пары: el chico — la chica '
        '(мальчик — девочка), el profesor — la profesora, el señor — la señora. У '
        'некоторых форма одна, меняется только артикль: el estudiante — la estudiante, el '
        'periodista — la periodista, el artista — la artista.\n\n'
        '4. НЕОПРЕДЕЛЁННЫЙ АРТИКЛЬ указывает на предмет как один из многих, впервые '
        'упоминаемый или неконкретный: un (м. р.), una (ж. р.): un libro (какая-то/одна '
        'книга), una mesa. Во множественном unos/unas значат «несколько, какие-то»: unos '
        'amigos (несколько друзей), unas casas. После глагола hay (есть, имеется) и в '
        'ряде оборотов артикль часто опускается: Hay leche (есть молоко); Soy profesor (я '
        'преподаватель).\n\n'
        '5. УКАЗАТЕЛЬНЫЕ СЛОВА esto (это) и eso (то) употребляются, когда предмет ещё не '
        'назван, и не меняются по родам: ¿Qué es esto? — Esto es un lápiz (Что это? — Это '
        'карандаш). Связка es («есть, является») — форма ser для 3-го лица; во '
        'множественном — son: Esos son unos libros (Это книги).\n\n'
        '6. МИНИ-ДИАЛОГ:\n'
        '— ¿Qué es esto? (Что это?)\n'
        '— Esto es un mapa y eso es una foto de mi ciudad. (Это карта, а то — фотография '
        'моего города.)\n'
        '— ¿Y aquello? ¿Es un problema de matemáticas? (А вон то? Это задача по '
        'математике?)\n'
        '— Sí. Es un problema difícil, pero tengo una solución. (Да. Задача трудная, но '
        'у меня есть решение.)'
    ),
    3: (
        'Определённый артикль указывает, что предмет известен собеседникам, единственный '
        'в своём роде или уже упоминался. Формы: el (м. р. ед.), la (ж. р. ед.), los '
        '(м. р. мн.), las (ж. р. мн.): el libro — los libros, la casa — las casas.\n\n'
        '1. ОСОБЫЙ СЛУЧАЙ: перед существительными женского рода, начинающимися с '
        'УДАРНОГО a- или ha-, в единственном числе ставится el: el agua (вода), el aula '
        '(аудитория), el hambre (голод). Род остаётся женским: el agua fría (холодная '
        'вода); во множественном возвращается las: las aguas.\n\n'
        '2. СЛИЯНИЯ С ПРЕДЛОГАМИ (обязательные): a + el = al (Voy al parque — иду в '
        'парк); de + el = del (el libro del profesor — книга преподавателя). С la, los, '
        'las слияния нет: de la casa, a los niños.\n\n'
        '3. ПРИЛАГАТЕЛЬНОЕ согласуется с существительным в роде и числе:\n'
        '• на -o меняют род: alto/alta, rojo/roja: el coche rojo, la casa roja;\n'
        '• на -e и на большинство согласных по роду НЕ меняются: grande, verde, azul, '
        'fácil: un libro verde, una mesa verde;\n'
        '• прилагательные национальности на согласную образуют женский род прибавлением '
        '-a: español → española, francés → francesa, alemán → alemana;\n'
        '• множественное число: +s после гласной (rojos), +es после согласной '
        '(azules, fáciles).\n\n'
        '4. МЕСТО ПРИЛАГАТЕЛЬНОГО. Обычное положение — ПОСЛЕ существительного: '
        'описательные признаки, цвета, форма, национальность: la mesa redonda (круглый '
        'стол), un escritor español. Перед существительным ставятся показатели '
        'количества и порядка (dos casas, primer día) и несколько кратких оценочных '
        'прилагательных.\n\n'
        '5. УСЕЧЕНИЕ (apócope). Перед существительным мужского рода ЕДИНСТВЕННОГО числа '
        'некоторые прилагательные теряют конечный слог: bueno → buen (un buen amigo), '
        'malo → mal (un mal día), primero → primer (el primer piso), tercero → tercer. '
        'А grande → gran перед существительным ЛЮБОГО рода в ед. ч.: un gran hombre '
        '(великий человек), una gran ciudad. Обратите внимание на смысл: ciudad grande '
        '(после — «большой по размеру») ↔ gran ciudad (перед — «великий, '
        'выдающийся»).\n\n'
        '6. МИНИ-ДИАЛОГ:\n'
        '— ¿Cómo es tu casa nueva? (Какой у тебя новый дом?)\n'
        '— Es una casa grande y luminosa, con las ventanas azules. (Большой и светлый '
        'дом, с синими окнами.)\n'
        '— ¡Qué bien! ¿Y el barrio? (Здорово! А район?)\n'
        '— Es un buen barrio, tranquilo. Del parque al centro se va a pie. (Хороший '
        'район, тихий. От парка до центра можно дойти пешком.)'
    ),
    4: (
        'Обычный порядок слов в испанском повествовательном предложении прямой: '
        'подлежащее + сказуемое + дополнения: María compra pan (Мария покупает хлеб). Но '
        'порядок гибче русского: прилагательные-определения обычно стоят ПОСЛЕ '
        'существительного, а местоимение-подлежащее часто опускается, ведь лицо видно по '
        'окончанию глагола: Hablo español (я говорю по-испански).\n\n'
        '1. ВОПРОСИТЕЛЬНОЕ ПРЕДЛОЖЕНИЕ. На письме вопрос обрамляется двумя знаками: '
        'перевёрнутым ¿ в начале и обычным ? в конце. В общем вопросе (да/нет) чаще '
        'делается инверсия — глагол выходит вперёд: ¿Habla usted español? ¿Vive María '
        'aquí? Возможен и прямой порядок с вопросительной интонацией: ¿María vive aquí?\n\n'
        '2. СПЕЦИАЛЬНЫЙ ВОПРОС строится с вопросительными словами (все с тильдой):\n'
        '• ¿qué? — что? какой?: ¿Qué es esto?;\n'
        '• ¿quién? / ¿quiénes? — кто?: ¿Quién es?;\n'
        '• ¿dónde? — где?, ¿adónde? — куда?: ¿Dónde vives?;\n'
        '• ¿cómo? — как?: ¿Cómo estás?;\n'
        '• ¿cuándo? — когда?, ¿cuánto? — сколько?, ¿por qué? — почему?\n'
        'После вопросительного слова глагол идёт перед подлежащим: ¿Dónde vive María?\n\n'
        '3. ОТРИЦАНИЕ. Частица no ставится непосредственно ПЕРЕД глаголом: No hablo '
        'francés; María no vive aquí. В кратком ответе no повторяется: ¿Hablas inglés? — '
        'No, no hablo inglés. Между no и глаголом могут вклиниться только '
        'местоимения-дополнения: No lo sé (я этого не знаю).\n\n'
        '4. ДВОЙНОЕ ОТРИЦАНИЕ — норма испанского. Отрицательные слова nada (ничего), '
        'nadie (никто), nunca / jamás (никогда), tampoco (тоже не), ninguno (никакой) '
        'ПОСЛЕ глагола требуют no перед ним: No veo nada; No viene nadie; No fumo nunca; '
        'Yo tampoco. Но если отрицательное слово стоит ПЕРЕД глаголом, no не нужно: Nadie '
        'viene; Nunca fumo.\n\n'
        '5. ПАРНЫЕ СОЮЗЫ. «и…и» — y (перед i-/hi- меняется на e: madre e hija); «или» — '
        'o (перед o-/ho- меняется на u: siete u ocho); «ни…ни» — ni… ni: No tengo ni '
        'tiempo ni ganas (у меня нет ни времени, ни желания).\n\n'
        '6. МИНИ-ДИАЛОГ:\n'
        '— ¿Dónde vive María? ¿Aquí? (Где живёт Мария? Здесь?)\n'
        '— No, no vive aquí. Y no conoce a nadie en el barrio. (Нет, здесь не живёт. И '
        'никого не знает в районе.)\n'
        '— ¿Por qué no viene nunca a las reuniones? (Почему она никогда не приходит на '
        'встречи?)\n'
        '— Ni idea. No tiene ni tiempo ni ganas, supongo. (Понятия не имею. Ни времени, '
        'ни желания, наверное.)'
    ),
}

THEORY_EXPAND_2B = {
    5: (
        'В испанском ДВА глагола «быть», и они не взаимозаменяемы: ser отвечает за '
        'сущность, estar — за состояние и место.\n\n'
        '1. SER — постоянная сущность. Настоящее: soy, eres, es, somos, sois, son. '
        'Употребляется для:\n'
        '• тождества и определения: Esto es un libro; Soy Iván;\n'
        '• профессии и рода занятий: Soy médico (я врач); Ella es estudiante;\n'
        '• происхождения и национальности: Soy de Rusia; Es español;\n'
        '• постоянных качеств: María es alta; El coche es rojo;\n'
        '• времени и дат: Es la una; Son las tres; Hoy es lunes;\n'
        '• материала и принадлежности: La mesa es de madera; El libro es de Ana.\n\n'
        '2. ESTAR — состояние и местоположение: estoy, estás, está, estamos, estáis, '
        'están (следите за ударениями). Употребляется для:\n'
        '• местонахождения: Estoy en casa; Madrid está en España; El libro está en la '
        'mesa;\n'
        '• временных состояний и самочувствия: Estoy cansado (я устал); La sopa está '
        'caliente (суп горячий — сейчас); ¿Cómo estás? — Estoy bien.\n\n'
        '3. КОНТРАСТНЫЕ ПАРЫ — там, где выбор глагола МЕНЯЕТ СМЫСЛ:\n'
        '• Es alegre (весёлый по характеру) ↔ Está alegre (сейчас весел);\n'
        '• La manzana es verde (зелёного цвета) ↔ La manzana está verde (неспелая);\n'
        '• Es rico (богатый) ↔ Está rico (вкусный — о еде);\n'
        '• Es aburrido (скучный человек) ↔ Está aburrido (ему скучно).\n'
        'Общий ориентир: ser = «какой это по сути», estar = «как сейчас / где».\n\n'
        '4. ПРЕДЛОГИ И НАРЕЧИЯ МЕСТА (обычно с estar):\n'
        '• en — в, на: en casa, en la mesa;\n'
        '• sobre / encima de — на, поверх: sobre la mesa;\n'
        '• bajo / debajo de — под: debajo de la cama;\n'
        '• delante de — перед; detrás de — за, позади;\n'
        '• enfrente de — напротив; entre — между: entre la ventana y la puerta;\n'
        '• al lado de — рядом с; cerca de — близко от; lejos de — далеко от.\n'
        'Пример: El banco está al lado de la farmacia, enfrente del parque (банк рядом с '
        'аптекой, напротив парка).\n\n'
        '5. МИНИ-ДИАЛОГ:\n'
        '— ¿Dónde estás? Te espero en el café. (Ты где? Жду тебя в кафе.)\n'
        '— Estoy cerca, al lado de la farmacia. ¿El café es el nuevo? (Я рядом, около '
        'аптеки. Кафе — то новое?)\n'
        '— Sí, es pequeño pero muy bonito. Y el camarero es de Sevilla. (Да, маленькое, '
        'но очень уютное. А официант из Севильи.)\n'
        '— ¡Perfecto! Estoy allí en dos minutos. (Отлично! Буду через две минуты.)'
    ),
    6: (
        '1. КОНСТРУКЦИЯ HAY. Особая безличная форма глагола haber означает «есть, '
        'имеется, находится». У неё ОДНА форма и для единственного, и для множественного '
        'числа: Hay un libro en la mesa (на столе книга); Hay muchos coches en la calle '
        '(на улице много машин); ¿Qué hay en la caja? (что в коробке?).\n\n'
        '2. HAY ПРОТИВ ESTÁ / ESTÁN — выбор по определённости:\n'
        '• hay вводит НОВОЕ, неизвестное — с неопределённым артиклем, числительными, '
        'словами mucho/poco/varios или вовсе без артикля: Hay una farmacia cerca; Hay '
        'dos ventanas; Hay pan;\n'
        '• estar говорит о месте ИЗВЕСТНОГО, конкретного предмета — с определённым '
        'артиклем, притяжательными, именами: La farmacia está cerca; El pan está en la '
        'mesa; María está en casa.\n'
        'Запрещено: *Hay la farmacia…, *El libro hay en la mesa.\n\n'
        '3. ВОПРОС О КОЛИЧЕСТВЕ с hay: ¿Cuántos alumnos hay en la clase? — Hay veinte. '
        '¿Hay leche? — Sí, hay / No, no hay.\n\n'
        '4. МЕСТО ПРИЛАГАТЕЛЬНОГО (продолжение). Описательные прилагательные, выделяющие '
        'предмет среди других (цвет, форма, размер, национальность), стоят ПОСЛЕ '
        'существительного: una casa blanca, un problema difícil. ПЕРЕД существительным '
        'ставятся:\n'
        '• числительные и слова количества: dos libros, muchas casas, pocos amigos;\n'
        '• указательные и притяжательные: este libro, mi casa;\n'
        '• оценочные bueno, malo, gran(de) — часто с усечением: un buen amigo, un mal '
        'día, una gran idea (отличная идея).\n\n'
        '5. ПРИЛАГАТЕЛЬНЫЕ, МЕНЯЮЩИЕ СМЫСЛ ОТ ПОЗИЦИИ:\n'
        '• un viejo amigo (давний друг) ↔ un amigo viejo (пожилой друг);\n'
        '• un gran hombre (великий) ↔ un hombre grande (крупный);\n'
        '• una pobre mujer (несчастная) ↔ una mujer pobre (бедная, без денег);\n'
        '• un antiguo profesor (бывший) ↔ un jarrón antiguo (старинный).\n\n'
        '6. МИНИ-ДИАЛОГ:\n'
        '— ¿Qué hay cerca de tu casa? (Что есть рядом с твоим домом?)\n'
        '— Hay un parque grande y dos cafés. El parque está justo enfrente. (Большой '
        'парк и два кафе. Парк прямо напротив.)\n'
        '— ¿Y hay alguna farmacia? (А аптека есть?)\n'
        '— Sí, hay una en la esquina. La farmacia está al lado del banco. (Да, есть на '
        'углу. Аптека рядом с банком.)'
    ),
    7: (
        'Множественное число существительных образуется по трём основным правилам.\n\n'
        '1. Слово оканчивается на БЕЗУДАРНУЮ ГЛАСНУЮ → добавляется -s: la casa → las '
        'casas, el coche → los coches, el estudiante → los estudiantes.\n\n'
        '2. Слово оканчивается на СОГЛАСНУЮ (а также на ударные -í / -ú у ряда слов) → '
        'добавляется -es: el profesor → los profesores, la ciudad → las ciudades, el '
        'español → los españoles, el rubí → los rubíes.\n\n'
        '3. Слово оканчивается на -z → z меняется на c и добавляется -es: el lápiz → los '
        'lápices, la vez → las veces, la luz → las luces.\n\n'
        '4. ОСОБЫЕ СЛУЧАИ:\n'
        '• слова на безударный слог с -s во мн. числе НЕ меняются — меняется только '
        'артикль: el lunes → los lunes, la crisis → las crisis, el paraguas → los '
        'paraguas;\n'
        '• тильда может исчезать или появляться, чтобы сохранить место ударения: la '
        'canción → las canciones, el examen → los exámenes, el joven → los jóvenes;\n'
        '• смешанная группа лиц обозначается мужским родом: los padres (родители), los '
        'hermanos (братья и сёстры), los reyes (король с королевой).\n\n'
        '5. АРТИКЛИ ВО МНОЖЕСТВЕННОМ: el → los, la → las; un → unos, una → unas '
        '(«несколько»).\n\n'
        '6. ПРИЛАГАТЕЛЬНЫЕ образуют мн. число по тем же правилам и согласуются с '
        'существительным: el coche rojo → los coches rojos; la casa grande → las casas '
        'grandes; el examen difícil → los exámenes difíciles.\n\n'
        '7. КОЛИЧЕСТВО. Вопрос cuánto согласуется как прилагательное: ¿Cuánto pan? '
        '¿Cuánta agua? ¿Cuántos libros? ¿Cuántas casas? Счёт до десяти: uno, dos, tres, '
        'cuatro, cinco, seis, siete, ocho, nueve, diez. uno перед существительным '
        'мужского рода усекается: un libro, но Tengo uno (у меня один); перед женским — '
        'una: una mesa.\n\n'
        '8. МИНИ-ДИАЛОГ:\n'
        '— ¿Cuántos exámenes tienes esta semana? (Сколько экзаменов у тебя на этой '
        'неделе?)\n'
        '— Tres: dos fáciles y uno difícil. (Три: два лёгких и один трудный.)\n'
        '— ¿Y los profesores son buenos? (А преподаватели хорошие?)\n'
        '— Sí, los tres son geniales. Las clases son los lunes y los jueves. (Да, все '
        'трое отличные. Занятия по понедельникам и четвергам.)'
    ),
    8: (
        'Существительное нередко употребляется ВОВСЕ БЕЗ артикля — это нулевой артикль. '
        'Его отсутствие тоже несёт смысл: предмет берётся неопределённо, как категория '
        'или вещество, а не как конкретная вещь.\n\n'
        '1. ПРОФЕССИЯ, НАЦИОНАЛЬНОСТЬ, РОД ЗАНЯТИЙ после ser: Soy médico; Es profesora; '
        'Son estudiantes. НО с определением возвращается неопределённый артикль: Es un '
        'buen médico; Es una profesora excelente.\n\n'
        '2. НЕИСЧИСЛЯЕМЫЕ ВЕЩЕСТВА и неопределённое количество после глагола: Bebo agua; '
        'Como pan; ¿Tienes dinero? Сравните с конкретным: El pan está en la mesa (тот '
        'самый хлеб — с артиклем).\n\n'
        '3. СУЩЕСТВИТЕЛЬНОЕ ВО МН. ЧИСЛЕ в общем значении: Compro libros (покупаю книги — '
        'вообще); Tiene amigos en Madrid; No como dulces.\n\n'
        '4. СТРАНЫ И ГОРОДА (большинство — без артикля): Vivo en España; Trabajo en '
        'Madrid; Vengo de Rusia. (Немногочисленные исключения-названия с артиклем '
        'встречаются, но их мало.)\n\n'
        '5. УСТОЙЧИВЫЕ СОЧЕТАНИЯ С ПРЕДЛОГАМИ: en casa (дома), a casa (домой), en clase '
        '(на занятии), por favor (пожалуйста), de memoria (наизусть), a pie (пешком), en '
        'coche (на машине), con gusto (с удовольствием).\n\n'
        '6. ПРИ ОБРАЩЕНИИ артикль опускается, а в рассказе о том же человеке — '
        'возвращается: ¡Buenos días, señor García! ↔ El señor García trabaja aquí. С '
        'don / doña артикля нет никогда: don Manuel, doña Carmen.\n\n'
        '7. ПОСЛЕ HAY вещество и неопределённое мн. число идут без артикля: Hay pan; Hay '
        'flores en el jarrón.\n\n'
        'ИТОГ-ОРИЕНТИР: конкретный известный предмет → el/la; один из многих, впервые → '
        'un/una; категория, вещество, профессия, устойчивый оборот → без артикля.\n\n'
        '8. МИНИ-ДИАЛОГ:\n'
        '— ¿Qué haces? ¿Eres estudiante? (Чем занимаешься? Ты студент?)\n'
        '— No, soy profesor. Bueno, soy un profesor con mucho trabajo. (Нет, я '
        'преподаватель. Точнее, преподаватель с кучей работы.)\n'
        '— ¿Y comes en casa o en la universidad? (А обедаешь дома или в '
        'университете?)\n'
        '— En casa. Con gusto: preparo pasta, bebo agua y descanso un poco. (Дома. С '
        'удовольствием: готовлю пасту, пью воду и немного отдыхаю.)'
    ),
}
THEORY_EXPAND_2A.update(THEORY_EXPAND_2B)

THEORY_EXPAND_2C = {
    9: (
        '1. ЛИЧНЫЕ МЕСТОИМЕНИЯ-ПОДЛЕЖАЩИЕ:\n'
        '• yo — я; tú — ты; él — он; ella — она; usted — Вы (вежливо, к одному '
        'человеку);\n'
        '• nosotros/nosotras — мы; vosotros/vosotras — вы (к нескольким «на ты», '
        'Испания); ellos/ellas — они; ustedes — Вы (к нескольким; в Латинской Америке — '
        'любое «вы» мн. ч.).\n'
        'Важно: usted и ustedes сочетаются с глаголом в ТРЕТЬЕМ лице: ¿Habla usted '
        'español? (Вы говорите по-испански?); ¿De dónde son ustedes?\n\n'
        '2. МЕСТОИМЕНИЕ-ПОДЛЕЖАЩЕЕ обычно ОПУСКАЕТСЯ, ведь окончание глагола уже '
        'показывает лицо и число: Hablo español (я говорю по-испански). Его ставят для '
        'контраста или уточнения: Yo trabajo y tú descansas (я работаю, а ты отдыхаешь); '
        'а также после ser: Soy yo (это я).\n\n'
        '3. ТРИ СПРЯЖЕНИЯ по окончанию инфинитива: -ar, -er, -ir. Первое (-ar) — самое '
        'многочисленное. Настоящее время образуется заменой -ar на личные окончания:\n'
        '  hablar: hablo, hablas, habla, hablamos, habláis, hablan.\n'
        'Так же спрягаются: trabajar, estudiar, comprar, escuchar, mirar, cantar, bailar, '
        'descansar, preguntar, contestar, llegar, tomar, viajar, cocinar.\n\n'
        '4. ЧТО ЗНАЧИТ НАСТОЯЩЕЕ ВРЕМЯ. Оно покрывает и действие «прямо сейчас», и '
        'регулярное, и общую истину: Trabajo en un banco (я работаю в банке); Estudiamos '
        'español; María canta muy bien; El agua hierve a cien grados (вода кипит при ста '
        'градусах). По-русски одно испанское hablo передаётся и «говорю», и «разговариваю '
        'вообще».\n\n'
        '5. ВОПРОС И ОТРИЦАНИЕ с -ar глаголами строятся как обычно: ¿Trabajas aquí? — No, '
        'no trabajo aquí; ¿Qué estudias? — Estudio Medicina; ¿Habláis inglés? — No, no '
        'hablamos inglés.\n\n'
        '6. МИНИ-ДИАЛОГ:\n'
        '— ¿Dónde trabajas y qué estudias? (Где ты работаешь и что изучаешь?)\n'
        '— Trabajo en una tienda y estudio español por las tardes. (Работаю в магазине, '
        'а по вечерам учу испанский.)\n'
        '— ¡Qué bien! Yo también estudio, pero canto en un coro los sábados. (Здорово! Я '
        'тоже учусь, но по субботам пою в хоре.)\n'
        '— ¿Cantas? ¡Qué envidia! Yo bailo fatal y canto peor. (Поёшь? Как я завидую! Я '
        'ужасно танцую и ещё хуже пою.)'
    ),
    10: (
        '1. СЛИЯНИЕ АРТИКЛЯ С ПРЕДЛОГАМИ. Предлоги a и de, встречаясь с артиклем el, '
        'ОБЯЗАТЕЛЬНО сливаются:\n'
        '• a + el = al: Voy al cine (иду в кино); Llegamos al centro;\n'
        '• de + el = del: Vengo del trabajo; la puerta del coche.\n'
        'С остальными артиклями слияния нет: a la escuela, de los amigos, a las chicas. '
        'Перед именами собственными с большой буквы тоже нет: Voy a El Escorial; una '
        'novela de El País.\n\n'
        '2. ГЛАГОЛЫ С ЧЕРЕДОВАНИЕМ e→ie. Корневая e под ударением превращается в ie — во '
        'всех формах ед. числа и в 3-м лице мн. числа; nosotros и vosotros сохраняют e '
        '(на них ударение не падает):\n'
        '  comenzar: comienzo, comienzas, comienza, comenzamos, comenzáis, comienzan.\n'
        'Так же: empezar (начинать), pensar (думать), cerrar (закрывать), despertar '
        '(будить), entender (понимать), perder (терять), preferir (предпочитать), а '
        'также querer: quiero, quieres, quiere, queremos, queréis, quieren. После '
        'comenzar / empezar перед инфинитивом ставится a: Comienzo a trabajar a las '
        'nueve.\n\n'
        '3. КОТОРЫЙ ЧАС. Время выражается глаголом ser:\n'
        '• Es la una (только для часа — ед. число);\n'
        '• Son las dos / las tres / las diez;\n'
        '• минуты: y — «с минутами», menos — «без»: Son las dos y diez (2:10); Son las '
        'tres menos cuarto (без четверти три); Es la una y media (полвторого);\n'
        '• y cuarto — четверть, y media — половина;\n'
        '• части суток: de la mañana (утра), de la tarde (дня), de la noche (вечера/'
        'ночи): a las ocho de la mañana.\n'
        'Вопрос: ¿Qué hora es? «Во сколько?» — ¿A qué hora…?; ответ с a: La clase '
        'comienza a las nueve; A la una — в час; en punto — ровно.\n\n'
        '4. МИНИ-ДИАЛОГ:\n'
        '— ¿A qué hora empieza la película? (Во сколько начинается фильм?)\n'
        '— A las ocho y media. ¿Quieres ir al cine del centro? (В полдевятого. Хочешь '
        'пойти в кино в центре?)\n'
        '— Sí, pero pienso llegar del trabajo a las ocho. (Да, но я думаю прийти с '
        'работы к восьми.)\n'
        '— Tranquilo, si empezamos a andar ya, llegamos en punto. (Спокойно, если '
        'выйдем прямо сейчас, придём ровно вовремя.)'
    ),
    11: (
        'Возвратные (местоименные) глаголы обозначают действие, направленное на самого '
        'себя, и в инфинитиве оканчиваются на -se: lavarse (умываться), levantarse '
        '(вставать), ducharse (принимать душ).\n\n'
        '1. ВОЗВРАТНЫЕ МЕСТОИМЕНИЯ: me, te, se, nos, os, se. Они меняются по лицам вместе '
        'с глаголом и ставятся ПЕРЕД спрягаемой формой:\n'
        '  lavarse: me lavo, te lavas, se lava, nos lavamos, os laváis, se lavan.\n\n'
        '2. РАЗНИЦА С НЕВОЗВРАТНЫМ употреблением — местоимение решает всё: Lavo el coche '
        '(мою машину) ↔ Me lavo (умываюсь); Despierto a mi hijo (бужу сына) ↔ Me '
        'despierto (просыпаюсь); Llamo a Ana (звоню Ане) ↔ Me llamo Ana (меня зовут '
        'Ана).\n\n'
        '3. ГЛАГОЛЫ РАСПОРЯДКА ДНЯ (многие с чередованием корня):\n'
        '• despertarse (e→ie) — просыпаться: Me despierto a las siete;\n'
        '• levantarse — вставать: Me levanto a las siete y diez;\n'
        '• ducharse — принимать душ; lavarse — умываться: Me lavo la cara y los dientes '
        '(с частями тела — определённый артикль, а не притяжательное!);\n'
        '• peinarse — причёсываться; vestirse (e→i) — одеваться: me visto;\n'
        '• acostarse (o→ue) — ложиться спать: Me acuesto a las once;\n'
        '• dormirse (o→ue) — засыпать. Сравните: dormir (спать) ↔ dormirse (засыпать).\n\n'
        '4. ОТРИЦАНИЕ И ВОПРОС. no ставится перед возвратным местоимением: No me levanto '
        'temprano. В вопросе порядок сохраняется: ¿A qué hora te levantas?; ¿Cómo te '
        'llamas?\n\n'
        '5. ПРИ ИНФИНИТИВЕ местоимение приклеивается к нему сзади и согласуется с '
        'подлежащим: Quiero ducharme; ¿Quieres levantarte?; Voy a acostarme pronto '
        '(лягу пораньше). Заметьте цепочку: quiero duchar-ME, quieres levantar-TE, va a '
        'acostar-SE.\n\n'
        '6. МИНИ-ДИАЛОГ:\n'
        '— ¿A qué hora te levantas los lunes? (Во сколько ты встаёшь по понедельникам?)\n'
        '— Me despierto a las seis, pero me levanto a las seis y media. (Просыпаюсь в '
        'шесть, но встаю в полседьмого.)\n'
        '— ¡Qué temprano! Yo prefiero acostarme tarde y dormir más. (Как рано! Я '
        'предпочитаю ложиться поздно и спать подольше.)\n'
        '— Yo también, pero tengo que ducharme y vestirme rápido. (Я тоже, но мне надо '
        'быстро принять душ и одеться.)'
    ),
    12: (
        '1. ВТОРОЕ СПРЯЖЕНИЕ — глаголы на -er. Настоящее время: замена -er на окончания '
        '-o, -es, -e, -emos, -éis, -en:\n'
        '  comer: como, comes, come, comemos, coméis, comen.\n'
        'Так же: beber (пить), leer (читать), aprender (учить), comprender (понимать), '
        'vender (продавать), responder (отвечать), creer (верить, полагать), correr '
        '(бегать). Окончания почти как у -ar, только с гласной e.\n\n'
        '2. ПАДЕЖНЫЕ ОТНОШЕНИЯ. В испанском НЕТ падежных окончаний — связи между словами '
        'передают ПРЕДЛОГИ:\n'
        '• родительный (кого? чего? чей?) → de: el libro de María (книга Марии), la '
        'capital de España, un vaso de agua (стакан воды);\n'
        '• дательный (кому? чему?) → a: Escribo una carta a mi madre; Vendo el coche a '
        'Juan;\n'
        '• винительный: без предлога для предметов (Leo un libro), но с ЛИЧНЫМ a для '
        'конкретных людей и одушевлённых: Veo a María; Comprendo a mi amigo; Espero a mi '
        'hermana. С предметом личного a нет: Espero el autobús.\n\n'
        '3. СЛИЯНИЯ действуют и здесь: de + el = del, a + el = al: la puerta del aula; '
        'Respondo al profesor (отвечаю преподавателю); el coche del vecino.\n\n'
        '4. ПОРЯДОК «СУЩЕСТВИТЕЛЬНОЕ + de + СУЩЕСТВИТЕЛЬНОЕ» заменяет русское '
        'притяжательное прилагательное: la mesa de madera (деревянный стол), el '
        'profesor de español (учитель испанского), la clase de historia (урок '
        'истории).\n\n'
        '5. ПРИМЕРЫ В ПРЕДЛОЖЕНИЯХ:\n'
        '• Como pan y bebo agua;\n'
        '• ¿Comprendes la pregunta del profesor?;\n'
        '• Los estudiantes aprenden español;\n'
        '• Leemos los libros de la biblioteca;\n'
        '• Vendo mi coche a un amigo de mi hermano;\n'
        '• No comprendo la letra de esta canción (я не понимаю слов этой песни).\n\n'
        '6. МИНИ-ДИАЛОГ:\n'
        '— ¿Qué lees? (Что читаешь?)\n'
        '— Un libro de historia de España. Aprendo mucho. (Книгу по истории Испании. '
        'Многое узнаю.)\n'
        '— ¿Y comprendes todo? (И всё понимаешь?)\n'
        '— Casi todo. Cuando no entiendo algo, pregunto a la profesora de la biblioteca. '
        '(Почти всё. Когда чего-то не понимаю, спрашиваю у библиотекаря.)'
    ),
}
THEORY_EXPAND_2A.update(THEORY_EXPAND_2C)
