# -*- coding: utf-8 -*-
"""Second content pass — theory expansion for lessons 13–22.

Only the 'theory' field is overridden (keyed by lesson number); exercises are left
intact. Presentation structure follows a classic textbook layout (numbered points,
contrastive tables, abundant translated examples, a closing mini-dialogue); all
wording and examples are original.
"""

THEORY_EXPAND_1 = {
    13: (
        '1. ТРЕТЬЕ СПРЯЖЕНИЕ — глаголы на -ir. В настоящем времени их окончания почти '
        'совпадают с -er и расходятся ТОЛЬКО в формах nosotros и vosotros:\n'
        '  vivir (жить): vivo, vives, vive, vivimos, vivís, viven\n'
        'Сравните ряды: comemos / coméis (-er) ↔ vivimos / vivís (-ir); в остальном '
        'окончания те же. Так же спрягаются: escribir (писать), abrir (открывать), '
        'recibir (получать), subir (подниматься), compartir (делить, делиться), '
        'decidir (решать), partir (уезжать). Примеры: Escribo un mensaje (я пишу '
        'сообщение); ¿A qué hora abrís? (во сколько вы открываете?); Compartimos piso '
        '(мы снимаем квартиру вместе).\n\n'
        '2. КЛЮЧЕВОЙ НЕПРАВИЛЬНЫЙ ГЛАГОЛ TENER (иметь): tengo, tienes, tiene, tenemos, '
        'tenéis, tienen. Форма yo особая (tengo), а в ударных формах e→ie (tienes, '
        'tiene, tienen). Tener кормит десятки оборотов, где по-русски мы говорим «мне…»:\n'
        '• возраст: Tengo veinte años (мне двадцать лет);\n'
        '• tener hambre / sed — быть голодным / хотеть пить: Tengo mucha hambre;\n'
        '• tener frío / calor / sueño — мёрзнуть / изнывать от жары / хотеть спать;\n'
        '• tener prisa — спешить; tener razón — быть правым; tener miedo — бояться;\n'
        '• tener ganas de + инфинитив — очень хотеть, «не терпится»: Tengo ganas de un '
        'café (очень хочу кофе); Tengo ganas de verte (не терпится тебя увидеть);\n'
        '• tener que + инфинитив — быть должным: Tengo que trabajar (мне надо '
        'работать).\n\n'
        '3. MUCHO И MUY — оба про «очень/много», но распределяются строго:\n'
        '• muy + ПРИЛАГАТЕЛЬНОЕ или НАРЕЧИЕ (не меняется): muy bueno, muy bien, muy '
        'tarde, muy cerca;\n'
        '• mucho + СУЩЕСТВИТЕЛЬНОЕ — согласуется в роде и числе: mucho trabajo, mucha '
        'agua, muchos libros, muchas ganas;\n'
        '• ГЛАГОЛ + mucho (форма застывшая): Trabajo mucho (я много работаю); Te lo '
        'agradezco mucho (очень тебе за это благодарен).\n'
        'Запрещено: *muy mucho, *muy trabajo, *mucho bueno.\n\n'
        '4. ДНИ НЕДЕЛИ (все мужского рода, со строчной буквы): lunes, martes, miércoles, '
        'jueves, viernes, sábado, domingo. «В понедельник» — el lunes; «по понедельникам» '
        '— los lunes: Los viernes recibo a mis amigos (по пятницам я принимаю друзей). '
        'El domingo no trabajo (в воскресенье я не работаю).\n\n'
        '5. МИНИ-ДИАЛОГ:\n'
        '— ¿Cuántos años tienes? (Сколько тебе лет?)\n'
        '— Tengo veinticinco. Y hoy tengo muchas ganas de salir. (Двадцать пять. И '
        'сегодня мне очень хочется куда-нибудь выбраться.)\n'
        '— Yo tengo que estudiar, pero los sábados tengo tiempo libre. (Мне надо '
        'заниматься, но по субботам я свободен.)\n'
        '— ¡Perfecto! El sábado escribimos a los demás y decidimos algo. (Отлично! В '
        'субботу напишем остальным и что-нибудь придумаем.)'
    ),
    14: (
        'Императив выражает просьбы, приказы, советы и приглашения: «сделай!», '
        '«послушай!», «проходите!».\n\n'
        '1. УТВЕРДИТЕЛЬНАЯ ФОРМА TÚ совпадает с формой 3-го лица ед. числа настоящего '
        'времени:\n'
        '• hablar → ¡Habla!, comer → ¡Come!, vivir → ¡Vive!;\n'
        '• escuchar → ¡Escucha! (послушай!), mirar → ¡Mira! (смотри!), perdonar → '
        '¡Perdona! (извини!), esperar → ¡Espera! (подожди!).\n'
        'Чередования корня сохраняются: cerrar → ¡Cierra la puerta! (закрой дверь!); '
        'pedir → ¡Pide un taxi!; volver → ¡Vuelve pronto! (возвращайся скорее!).\n\n'
        '2. ВОСЕМЬ НЕПРАВИЛЬНЫХ ФОРМ TÚ — коротышки, которые учат хором:\n'
        '  hacer → haz, poner → pon, salir → sal, tener → ten, venir → ven, decir → di, '
        'ir → ve, ser → sé.\n'
        '¡Haz la tarea! (сделай задание!) ¡Ven aquí! (иди сюда!) ¡Di la verdad! (скажи '
        'правду!) ¡Ten paciencia! (имей терпение!) ¡Sal de ahí! (выйди оттуда!)\n\n'
        '3. ВЕЖЛИВАЯ ФОРМА USTED и множественное. Форма usted берётся из subjuntivo '
        '(пока запомним частые): hablar → hable, comer → coma, hacer → haga, venir → '
        'venga, pasar → pase. ¡Pase, por favor! (проходите!) ¡Perdone! (извините!) '
        '¡Dígame! (слушаю вас! — по телефону). Форма vosotros проще всего: у инфинитива '
        '-r меняется на -d: ¡Hablad!, ¡Comed!, ¡Venid!, ¡Escuchad!\n\n'
        '4. МЕСТОИМЕНИЯ приклеиваются к утвердительному императиву СЗАДИ, слитно, часто '
        'с появлением письменного ударения:\n'
        '• ¡Dime! (скажи мне!) ¡Dame el libro! (дай мне книгу!) ¡Dámelo! (дай мне его!);\n'
        '• ¡Dale saludos a tu madre! (передавай привет маме!);\n'
        '• возвратные: ¡Levántate! (вставай!) ¡Siéntate! (садись!) ¡Cálmate! '
        '(успокойся!).\n\n'
        '5. ЖИВЫЕ «КОМАНДОЧКИ» разговора: ¡Oye! (слушай!), ¡Mira! (смотри/гляди!), '
        '¡Venga! (ну давай!), ¡Dale! (давай, вперёд!), ¡Vamos! (пошли!), ¡Cuídate! '
        '(береги себя!). А глагол querer помогает попросить мягко: ¿Quieres abrir la '
        'ventana? (откроешь окно?); Quiero un café, por favor (мне кофе, пожалуйста).\n\n'
        '6. МИНИ-ДИАЛОГ:\n'
        '— ¡Oye, ayúdame un momento, por favor! (Слушай, помоги мне на минутку, '
        'пожалуйста!)\n'
        '— ¡Claro! Dime qué hago. (Конечно! Скажи, что делать.)\n'
        '— Pon los libros en la mesa y ven a la cocina. (Положи книги на стол и иди на '
        'кухню.)\n'
        '— Vale, ¡voy! Y tú, ¡ten cuidado con esa caja! (Ладно, иду! А ты осторожнее с '
        'той коробкой!)'
    ),
    15: (
        '1. ПРИТЯЖАТЕЛЬНЫЕ ПРИЛАГАТЕЛЬНЫЕ ставятся ПЕРЕД существительным и заменяют '
        'артикль — вместе они не употребляются (нельзя *el mi libro):\n'
        '  mi — мой/моя; tu — твой/твоя; su — его/её/Ваш;\n'
        '  nuestro/nuestra — наш/наша; vuestro/vuestra — ваш/ваша; su — их/Ваш '
        '(ustedes).\n\n'
        '2. СОГЛАСОВАНИЕ. Все формы согласуются в ЧИСЛЕ (mi → mis, tu → tus, su → sus), '
        'а nuestro и vuestro — ещё и в РОДЕ:\n'
        '• mi casa → mis casas (мой дом → мои дома);\n'
        '• tu amigo → tus amigos;\n'
        '• nuestro coche, nuestra familia, nuestros hijos, nuestras hijas;\n'
        '• vuestro piso, vuestras ideas.\n'
        'Важнейшее правило: род и число согласуются с ПРЕДМЕТОМ обладания, а НЕ с '
        'владельцем. Поэтому su libro значит и «его книга», и «её книга» — предмет один '
        '(libro, м. р. ед. ч.), а хозяин может быть любым.\n\n'
        '3. МНОГОЗНАЧНОЕ SU. Форма su/sus покрывает сразу «его, её, Ваш (usted), их, Ваш '
        '(ustedes)». Если контекста мало, уточняют оборотом de + местоимение: el coche '
        'de él (его машина), la casa de ella, el libro de usted, la idea de ellos.\n\n'
        '4. ЧАСТИ ТЕЛА И ОДЕЖДА — ловушка для иностранца. Там, где русский ставит '
        '«свой», испанский с возвратными глаголами предпочитает АРТИКЛЬ, а не '
        'притяжательное: Me lavo las manos (мою руки, а не *mis manos); Se pone el '
        'abrigo (надевает пальто); Me duele la cabeza (у меня болит голова).\n\n'
        '5. ТРИ ПОЛЕЗНЫХ НЕПРАВИЛЬНЫХ ГЛАГОЛА (неправильна форма yo; у venir ещё e→ie в '
        'ударных формах):\n'
        '• salir (выходить, уходить): salgo, sales, sale, salimos, salís, salen — Salgo '
        'de casa a las ocho (выхожу из дома в восемь);\n'
        '• oír (слышать): oigo, oyes, oye, oímos, oís, oyen — ¿Me oyes? (ты меня '
        'слышишь?);\n'
        '• venir (приходить): vengo, vienes, viene, venimos, venís, vienen — ¿Vienes a '
        'mi fiesta? (придёшь на мой праздник?).\n\n'
        '6. МИНИ-ДИАЛОГ:\n'
        '— ¡Oye! ¿Vienes a nuestra cena el sábado? (Слушай! Придёшь на наш ужин в '
        'субботу?)\n'
        '— ¡Me encantaría! ¿Viene también tu hermana? (С удовольствием! Твоя сестра '
        'тоже придёт?)\n'
        '— Sí, y trae a su novio. Su coche es grande: cabemos todos. (Да, и приведёт '
        'своего парня. Его машина большая — мы все поместимся.)\n'
        '— ¡Perfecto! Salgo del trabajo a las seis y voy directo. (Отлично! Я выхожу с '
        'работы в шесть и еду прямо к вам.)'
    ),
    16: (
        '1. ГЛАГОЛ IR (идти, ехать) — один из самых неправильных и самых нужных в языке:\n'
        '  voy, vas, va, vamos, vais, van\n'
        'С направлением всегда идёт предлог a (a + el = al): Voy al trabajo (еду на '
        'работу); Vamos a la playa (едем на пляж); ¿Vas al centro? (ты в центр?). '
        'Способ передвижения — предлог en: en coche, en tren, en metro, en autobús, en '
        'avión; а «пешком» — устойчивое a pie.\n\n'
        '2. КОНСТРУКЦИЯ IR A + ИНФИНИТИВ — ближайшее будущее: планы, намерения, то, что '
        'вот-вот произойдёт (прямой аналог английского going to):\n'
        '• Voy a estudiar esta noche (сегодня вечером я буду заниматься);\n'
        '• ¿Qué vas a hacer mañana? (что ты будешь делать завтра?);\n'
        '• Vamos a viajar este verano (этим летом мы поедем путешествовать);\n'
        '• Van a comprar una casa (они собираются купить дом).\n'
        'Отрицание ставится перед всей конструкцией: No voy a salir hoy (сегодня я не '
        'пойду гулять).\n\n'
        '3. VAMOS A + ИНФИНИТИВ имеет и второе значение — «давай(те)…», побуждение к '
        'совместному действию: ¡Vamos a comer! (давайте есть!); ¡Vamos a ver! '
        '(посмотрим!); Vamos a empezar (давайте начнём).\n\n'
        '4. СЛОВА-МАРКЕРЫ БУДУЩЕГО помогают распознать эту конструкцию: hoy (сегодня), '
        'esta noche (сегодня вечером), luego (потом), más tarde (позже), mañana '
        '(завтра), pasado mañana (послезавтра), este fin de semana (в эти выходные), la '
        'semana que viene (на следующей неделе), el mes / el año que viene (в следующем '
        'месяце / году).\n\n'
        '5. ЕЩЁ ДВА ГЛАГОЛА С НЕПРАВИЛЬНЫМ YO пополняют копилку: poner (класть, ставить) '
        '→ pongo, pones, pone, ponemos, ponéis, ponen; traer (приносить) → traigo, '
        'traes, trae, traemos, traéis, traen. Voy a poner la mesa (я накрою на стол); '
        'Traigo el postre (я принесу десерт).\n\n'
        '6. МИНИ-ДИАЛОГ О ПЛАНАХ:\n'
        '— ¿Qué vas a hacer el sábado? (Что будешь делать в субботу?)\n'
        '— Voy a ir al cine con mi hermana. ¿Vienes? (Пойду в кино с сестрой. Пойдёшь?)\n'
        '— ¡Me encantaría poder ir, pero tengo que trabajar! (Я бы с удовольствием, но '
        'мне надо работать!)\n'
        '— ¡Qué pena! Bueno, ¡que te vaya bien! (Как жаль! Ну, удачи тебе!)'
    ),
    17: (
        'Pretérito imperfecto — первое прошедшее время курса. Оно отвечает на вопросы '
        '«что делал (обычно)? каким было?» и рисует прошлое ИЗНУТРИ, как длящийся фон, а '
        'не как отдельное завершённое событие.\n\n'
        '1. ТРИ ГЛАВНЫЕ РАБОТЫ imperfecto:\n'
        '• привычки и повторяющиеся действия: Antes jugaba al fútbol todos los días '
        '(раньше я играл в футбол каждый день);\n'
        '• фон, обстановка, погода, состояние: Hacía frío y llovía (было холодно и шёл '
        'дождь); La casa estaba en silencio (в доме было тихо);\n'
        '• возраст, время, внешность и чувства в прошлом: Tenía diez años (мне было '
        'десять); Eran las tres (было три часа); Estábamos muy contentos (мы были очень '
        'рады).\n\n'
        '2. ОБРАЗОВАНИЕ — окончания присоединяются к основе:\n'
        '• -ar: -aba, -abas, -aba, -ábamos, -abais, -aban\n'
        '  hablar: hablaba, hablabas, hablaba, hablábamos, hablabais, hablaban;\n'
        '• -er / -ir (окончания общие): -ía, -ías, -ía, -íamos, -íais, -ían\n'
        '  comer: comía, comías, comía…; vivir: vivía, vivías, vivía…\n'
        'Формы yo и él/ella совпадают (yo hablaba = él hablaba) — лицо подсказывает '
        'контекст или местоимение.\n\n'
        '3. ВСЕГО ТРИ НЕПРАВИЛЬНЫХ ГЛАГОЛА в imperfecto — их учат наизусть, и это '
        'практически весь список исключений на всё время:\n'
        '• ser → era, eras, era, éramos, erais, eran: Era una persona tranquila (он был '
        'спокойным человеком);\n'
        '• ir → iba, ibas, iba, íbamos, ibais, iban: Íbamos al mar cada verano (мы '
        'ездили на море каждое лето);\n'
        '• ver → veía, veías, veía…: De niño veía dibujos cada tarde (в детстве я каждый '
        'вечер смотрел мультики).\n\n'
        '4. СЛОВА-МАРКЕРЫ imperfecto настраивают на «длящееся прошлое»: antes (раньше), '
        'siempre (всегда), a menudo (часто), todos los días (каждый день), cada verano '
        '(каждое лето), normalmente, mientras (пока), de niño / de pequeño (в детстве), '
        'cuando era joven (когда был молодым).\n\n'
        '5. МИНИ-ДИАЛОГ:\n'
        '— ¿Cómo era tu pueblo de pequeño? (Каким был твой городок в детстве?)\n'
        '— Era muy tranquilo. Todos se conocían y los niños jugábamos en la calle. '
        '(Очень тихим. Все друг друга знали, а мы, дети, играли на улице.)\n'
        '— ¡Qué bonito! ¿E ibas mucho al campo? (Как здорово! И ты часто ездил за '
        'город?)\n'
        '— Sí, cada domingo. Veía a mis abuelos y comíamos todos juntos. (Да, каждое '
        'воскресенье. Я навещал бабушку с дедушкой, и мы обедали все вместе.)'
    ),
}

_EXPAND_2 = {
    18: (
        'Вопросительные слова (interrogativos) — каркас любого вопроса. Все они пишутся '
        'с тильдой и всегда стоят в начале, между перевёрнутым ¿ и обычным ?.\n\n'
        '1. ОСНОВНОЙ НАБОР:\n'
        '• qué — что / какой: ¿Qué quieres? (что ты хочешь?) ¿Qué hora es? (который '
        'час?);\n'
        '• quién / quiénes — кто: ¿Quién llama? (кто звонит?) ¿Quiénes vienen? (кто '
        'придёт — о многих?);\n'
        '• cómo — как: ¿Cómo estás? ¿Cómo te llamas?;\n'
        '• dónde — где, a dónde / adónde — куда, de dónde — откуда: ¿Dónde vives? '
        '¿Adónde vas? ¿De dónde eres? — Soy de Rusia;\n'
        '• cuándo — когда: ¿Cuándo llegas?;\n'
        '• cuánto/-a/-os/-as — сколько (согласуется!): ¿Cuánto cuesta? (сколько стоит?) '
        '¿Cuántos años tienes? ¿Cuánta gente hay?;\n'
        '• por qué — почему (раздельно!) ↔ ответ porque — потому что (слитно): ¿Por qué '
        'no vienes? — Porque tengo que trabajar;\n'
        '• cuál / cuáles — какой (из нескольких), который: ¿Cuál prefieres? (какой '
        'предпочитаешь?).\n\n'
        '2. ПРЕДЛОГ ИДЁТ ВПЕРЕДИ вопросительного слова — в отличие от русского и '
        'английского, он не «повисает» в конце:\n'
        '• ¿De qué habláis? (о чём вы говорите?) — Hablamos de la película;\n'
        '• ¿A quién esperas? (кого ты ждёшь?) — Espero a María;\n'
        '• ¿Para quién es el regalo? (для кого подарок?);\n'
        '• ¿Con quién vas? (с кем ты идёшь?);\n'
        '• ¿En qué trabajas? (кем ты работаешь? досл. «в чём»);\n'
        '• ¿De quién es este coche? (чья это машина?).\n\n'
        '3. QUÉ ПРОТИВ CUÁL — частая путаница:\n'
        '• qué + существительное или для определения/понятия: ¿Qué libro lees? ¿Qué es '
        'esto?;\n'
        '• cuál — выбор из известного множества, обычно без существительного: ¿Cuál es '
        'tu color favorito? (какой твой любимый цвет?) ¿Cuál quieres, el rojo o el azul?\n\n'
        '4. КОСВЕННЫЙ ВОПРОС сохраняет то же слово с тильдой, но уже без знаков ¿?: No sé '
        'qué hacer (не знаю, что делать); Dime dónde estás (скажи, где ты); Pregunta '
        'cuándo llega (спроси, когда он приедет).\n\n'
        '5. МИНИ-ДИАЛОГ:\n'
        '— ¿De dónde eres y a qué te dedicas? (Откуда ты и чем занимаешься?)\n'
        '— Soy de Kiev y trabajo en marketing. ¿Y tú? (Я из Киева, работаю в '
        'маркетинге. А ты?)\n'
        '— Yo soy de Madrid. Oye, ¿por qué estudias español? (Я из Мадрида. Слушай, а '
        'почему ты учишь испанский?)\n'
        '— Porque me encanta la cultura. ¿Cuál es tu ciudad favorita de España? (Потому '
        'что обожаю здешнюю культуру. А какой твой любимый город в Испании?)'
    ),
    19: (
        '1. СРАВНЕНИЕ РАВЕНСТВА tanto / tan — «такой же… как», «столько же… сколько».\n'
        '• tan + ПРИЛАГАТЕЛЬНОЕ или НАРЕЧИЕ + como: Es tan alto como su padre (он такой '
        'же высокий, как его отец); Habla tan rápido como tú (он говорит так же быстро, '
        'как ты);\n'
        '• tanto/-a/-os/-as + СУЩЕСТВИТЕЛЬНОЕ + como (согласуется в роде и числе!): '
        'Tengo tantos libros como tú (у меня столько же книг, сколько у тебя); Hay tanta '
        'gente como ayer (народу столько же, сколько вчера);\n'
        '• ГЛАГОЛ + tanto como: Trabaja tanto como yo (он работает столько же, сколько '
        'я).\n'
        'В восклицаниях tan/tanto усиливают: ¡Es tan bonito! (это так красиво!) ¡Tanto '
        'tiempo sin verte! (сколько лет, сколько зим!).\n\n'
        '2. НАПОМНИМ СОСЕДНИЕ СТУПЕНИ СРАВНЕНИЯ (для контраста):\n'
        '• больше/меньше: más… que / menos… que — Soy más alto que él;\n'
        '• равенство: tan/tanto… como (эта тема);\n'
        '• неправильные: mejor (лучше), peor (хуже), mayor (старше/больше), menor '
        '(младше/меньше): Este café es mejor que el otro.\n\n'
        '3. ОПИСАНИЕ ВНЕШНОСТИ — постоянные черты через ser и tener:\n'
        '• рост и сложение (ser): alto (высокий), bajo (низкий), delgado (худой), fuerte '
        '(крепкий), guapo (красивый), joven (молодой), mayor (пожилой);\n'
        '• волосы (tener + артикль): Tiene el pelo largo / corto / rubio / moreno / '
        'rizado / liso (длинные / короткие / светлые / тёмные / кудрявые / прямые '
        'волосы);\n'
        '• глаза (tener): Tiene los ojos azules / verdes / marrones / negros;\n'
        '• аксессуары (llevar): lleva gafas / barba / bigote (носит очки / бороду / '
        'усы).\n\n'
        '4. ПОДВИЖНЫЕ СОСТОЯНИЯ — через estar (в отличие от постоянных черт): Está '
        'cansado (он устал), Está contento (он доволен), Está enfadada (она сердится). '
        'Сравните: Es nervioso (он нервный по натуре) ↔ Está nervioso (он сейчас '
        'нервничает).\n\n'
        '5. ПОРТРЕТ-ПРИМЕР: Mi hermana es alta y delgada, tiene el pelo moreno y los '
        'ojos verdes, y es tan simpática como mi madre. Hoy está un poco cansada, pero '
        'siempre sonríe. Que yo sepa, no lleva gafas (моя сестра высокая и стройная, у '
        'неё тёмные волосы и зелёные глаза, и она такая же милая, как мама. Сегодня она '
        'немного устала, но всегда улыбается. Насколько я знаю, очков она не носит).\n\n'
        '6. МИНИ-ДИАЛОГ:\n'
        '— ¿Cómo es tu hermano? (Какой твой брат?)\n'
        '— Es tan alto como yo, pero más deportista. Tiene el pelo rizado. (Такой же '
        'высокий, как я, но спортивнее. У него кудрявые волосы.)\n'
        '— ¿Y os parecéis de carácter? (А по характеру вы похожи?)\n'
        '— Bastante. Él es tan tranquilo como yo, aunque hoy está nervioso por un '
        'examen. (Довольно. Он такой же спокойный, как я, хотя сегодня нервничает из-за '
        'экзамена.)'
    ),
    20: (
        '1. МЕСТОИМЕНИЯ-ДОПОЛНЕНИЯ заменяют существительные, чтобы не повторяться.\n\n'
        'ПРЯМОЕ дополнение (кого? что?): me, te, lo/la, nos, os, los/las:\n'
        '• ¿Ves a Ana? — Sí, la veo (да, я её вижу);\n'
        '• ¿Compras el pan? — Sí, lo compro;\n'
        '• ¿Nos escuchas? — Sí, os escucho.\n\n'
        'КОСВЕННОЕ дополнение (кому? чему?): me, te, le, nos, os, les:\n'
        '• Le escribo una carta (a María) — я пишу ей письмо;\n'
        '• Les doy las gracias (a mis padres) — я благодарю их.\n'
        'Формы различаются ТОЛЬКО в 3-м лице: прямое lo/la/los/las ↔ косвенное le/les.\n\n'
        '2. МЕСТО местоимения: перед спрягаемым глаголом (Lo veo. No lo veo) или '
        'приклеенным к инфинитиву — оба варианта верны: Quiero verlo = Lo quiero ver '
        '(хочу это увидеть). При двух местоимениях сначала косвенное, потом прямое, а le '
        '+ lo превращается в se lo: Se lo doy (я даю это ему).\n\n'
        '3. ТРИ ГЛАГОЛА, КОТОРЫЕ ПУТАЮТ:\n'
        '• poder (o→ue) — мочь (возможность, разрешение): puedo, puedes, puede, podemos, '
        'podéis, pueden. ¿Puedo pasar? (можно войти?) No puedo ir hoy;\n'
        '• saber — знать факт/информацию, УМЕТЬ (навык): sé, sabes, sabe, sabemos, '
        'sabéis, saben. Sé la respuesta (я знаю ответ); Sé nadar (я умею плавать); Que '
        'yo sepa… (насколько я знаю…);\n'
        '• conocer — быть ЗНАКОМЫМ с человеком или местом: conozco, conoces, conoce… '
        'Conozco a María (я знаком с Марией); ¿Conoces Madrid? (ты бывал в Мадриде?).\n\n'
        '4. SABER ПРОТИВ CONOCER, PODER ПРОТИВ SABER — тонкая грань:\n'
        '• Sé dónde vive (знаю адрес — информация) ↔ Conozco su casa (бывал там — '
        'знаком);\n'
        '• Sé nadar (умею в принципе — навык) ↔ Puedo nadar hoy (могу сегодня — есть '
        'возможность).\n\n'
        '5. ЛИЧНОЕ A с дополнением-человеком обязательно, а при замене местоимением '
        'исчезает: Conozco a tu hermano → Lo conozco; Veo a los niños → Los veo; Espero '
        'a María → La espero.\n\n'
        '6. МИНИ-ДИАЛОГ:\n'
        '— ¿Conoces a mi primo Diego? (Ты знаком с моим двоюродным братом Диего?)\n'
        '— No lo conozco, pero sé quién es. ¿Puedes presentármelo? (Я с ним не знаком, '
        'но знаю, кто это. Можешь меня с ним познакомить?)\n'
        '— Claro, lo llamo ahora. Él sabe mucho de música, como tú. (Конечно, сейчас '
        'ему позвоню. Он, как и ты, здорово разбирается в музыке.)\n'
        '— ¡Genial! Que yo sepa, tocamos la misma guitarra. (Отлично! Насколько я знаю, '
        'мы играем на одинаковых гитарах.)'
    ),
    21: (
        '1. КОНСТРУКЦИЯ С SE позволяет говорить обобщённо, не называя деятеля — по-русски '
        '«здесь говорят», «продаётся», «так делают». Это опора вывесок, объявлений, '
        'инструкций и рассказа об обычаях.\n\n'
        '2. ПАССИВНО-ВОЗВРАТНАЯ ФОРМА: se + глагол, СОГЛАСОВАННЫЙ С ПРЕДМЕТОМ (ед. или '
        'мн. число — по существительному!):\n'
        '• Se vende piso (продаётся квартира) → Se venden pisos (продаются квартиры);\n'
        '• Se habla español (здесь говорят по-испански);\n'
        '• Se necesitan camareros (требуются официанты);\n'
        '• Se alquila habitación (сдаётся комната);\n'
        '• ¿Cómo se escribe tu nombre? (как пишется твоё имя?).\n\n'
        '3. ЧИСТО БЕЗЛИЧНАЯ ФОРМА: se + глагол ТОЛЬКО в ед. числе — об образе жизни, '
        'правилах, обычаях (подлежащего нет вовсе):\n'
        '• En España se cena tarde (в Испании ужинают поздно);\n'
        '• Aquí se trabaja mucho (здесь много работают);\n'
        '• No se puede fumar aquí (здесь нельзя курить);\n'
        '• ¿Cómo se dice «спасибо» en español? — Se dice «gracias».\n'
        'Удобная формула вежливого запрета/разрешения: (no) se puede + инфинитив.\n\n'
        '4. SE DICE QUE… (говорят, что…) — способ передать слух или общее мнение: Se '
        'dice que este restaurante es muy bueno (говорят, этот ресторан очень хорош); Se '
        'cree que va a llover (считается, что будет дождь).\n\n'
        '5. СОГЛАСОВАНИЕ ПРИЛАГАТЕЛЬНЫХ (повторение на новом материале): прилагательное '
        'согласуется с существительным всегда, в том числе в se-конструкциях: Se venden '
        'coches usados (продаются подержанные машины); Se alquila habitación luminosa '
        '(сдаётся светлая комната); Se buscan personas responsables (ищем ответственных '
        'людей).\n\n'
        '6. МИНИ-ОБЪЯВЛЕНИЯ — типичное место se-конструкций: SE VENDE, SE ALQUILA, SE '
        'BUSCA, SE NECESITA, SE TRASPASA.\n\n'
        '7. МИНИ-ДИАЛОГ:\n'
        '— Perdona, ¿se puede aparcar aquí? (Извините, здесь можно парковаться?)\n'
        '— No, aquí no se puede. Pero se aparca bien en la plaza. (Нет, здесь нельзя. '
        'Зато на площади паркуются свободно.)\n'
        '— Gracias. Y dime, ¿cómo se llega al centro? (Спасибо. И скажите, как добраться '
        'до центра?)\n'
        '— Se va todo recto. Por cierto, se dice que hay un mercado precioso allí. '
        '(Идите всё прямо. Кстати, говорят, там есть чудесный рынок.)'
    ),
    22: (
        'Pretérito perfecto — «прошлое, связанное с настоящим»: недавние события и '
        'жизненный опыт «до сих пор».\n\n'
        '1. ОБРАЗОВАНИЕ: haber (в настоящем) + participio (причастие).\n'
        '  haber: he, has, ha, hemos, habéis, han\n'
        '  причастие: -ar → -ado (hablado), -er / -ir → -ido (comido, vivido).\n'
        'He trabajado mucho hoy (я сегодня много работал); ¿Has comido? (ты поел?). '
        'Между haber и причастием ничего не вставляется, а местоимения ставятся перед '
        'haber: Lo he visto (я это видел); No he terminado (я не закончил).\n\n'
        '2. НЕПРАВИЛЬНЫЕ ПРИЧАСТИЯ — короткий список, который надо знать наизусть:\n'
        '• ver → visto, hacer → hecho, decir → dicho, escribir → escrito;\n'
        '• poner → puesto, volver → vuelto, abrir → abierto, romper → roto;\n'
        '• morir → muerto, cubrir → cubierto.\n'
        'He hecho la cama (я застелил постель); ¿Has visto las llaves? (ты видел '
        'ключи?); No ha vuelto todavía (он ещё не вернулся).\n\n'
        '3. КОГДА УПОТРЕБЛЯЕТСЯ:\n'
        '• период, который ещё длится: hoy, esta semana, este mes, este año, esta '
        'mañana — Esta semana hemos estudiado mucho;\n'
        '• жизненный опыт: alguna vez (когда-нибудь), nunca (никогда), ya (уже), todavía '
        'no (ещё нет) — ¿Has estado alguna vez en México? — No, nunca he estado; Nunca '
        'he visto nada parecido;\n'
        '• результат к настоящему: ¿Cómo te ha ido el examen? (как прошёл экзамен?); Ha '
        'sido un día difícil (день выдался трудным).\n\n'
        '4. СЧЁТ ДО 100 (пригодится для дат и количеств): 11 once, 12 doce, 13 trece, 14 '
        'catorce, 15 quince, 16 dieciséis, 20 veinte, 21 veintiuno, 30 treinta, 31 '
        'treinta y uno, 40 cuarenta, 50 cincuenta, 60 sesenta, 70 setenta, 80 ochenta, '
        '90 noventa, 100 cien. От 31 и выше — через y: cuarenta y cinco (45), sesenta y '
        'ocho (68).\n\n'
        '5. МИНИ-ДИАЛОГ:\n'
        '— ¿Cómo te ha ido el examen? (Как прошёл экзамен?)\n'
        '— ¡Muy bien! He contestado todas las preguntas. (Отлично! Я ответил на все '
        'вопросы.)\n'
        '— ¡Cuánto me alegro! ¿Y ya has visto la nota? (Как я рад! А оценку ты уже '
        'видел?)\n'
        '— Todavía no, pero esta semana ha sido genial. (Ещё нет, но неделя выдалась '
        'отличной.)'
    ),
}
THEORY_EXPAND_1.update(_EXPAND_2)
