# -*- coding: utf-8 -*-
"""Original role-play simulations (license-clean), 4 per CEFR level A1->C2, graded by
difficulty. Each is a mini-mission: the AI plays a role, the learner must reach a goal,
with hint phrases and a per-turn goal-achievement judgement.

Titles/goals are localized; role/goal_es/setup_es/hints are Spanish (the practice content).
"""


def _s(id, level, title, role, goal, goal_es, setup_es, hints):
    return {'id': id, 'level': level, 'title': title, 'role': role, 'goal': goal,
            'goal_es': goal_es, 'setup_es': setup_es, 'hints': hints}


SCENARIOS = [
    # ---------------- A1 ----------------
    _s('a1_cafe', 'A1',
       {'es': 'Pedir en un café', 'ru': 'Заказ в кафе', 'uk': 'Замовлення в кафе', 'ar': 'الطلب في مقهى', 'fr': 'Commander au café', 'en': 'Order at a café'},
       'camarero de una cafetería',
       {'es': 'Pedir un café y algo de comer', 'ru': 'Заказать кофе и что-нибудь поесть', 'uk': 'Замовити каву та щось поїсти', 'ar': 'طلب قهوة وشيء للأكل', 'fr': 'Commander un café et à manger', 'en': 'Order a coffee and something to eat'},
       'El estudiante debe pedir una bebida y algo de comer, y preguntar el precio.',
       'Entras en una cafetería y quieres desayunar.',
       ['Buenos días, ¿me pone un café?', 'También quiero un croissant.', '¿Cuánto es?']),
    _s('a1_presentarse', 'A1',
       {'es': 'Conocer a alguien', 'ru': 'Знакомство', 'uk': 'Знайомство', 'ar': 'التعارف', 'fr': 'Faire connaissance', 'en': 'Meeting someone'},
       'una persona nueva en una fiesta',
       {'es': 'Presentarte: nombre, origen y profesión', 'ru': 'Представиться: имя, откуда, профессия', 'uk': 'Представитися: імʼя, звідки, професія', 'ar': 'التعريف بنفسك: الاسم والأصل والمهنة', 'fr': 'Te présenter : nom, origine, métier', 'en': 'Introduce yourself: name, origin, job'},
       'El estudiante debe decir su nombre, de dónde es y a qué se dedica, y preguntar lo mismo.',
       'Estás en una fiesta y conoces a alguien.',
       ['Hola, me llamo...', 'Soy de...', '¿Y tú, a qué te dedicas?']),
    _s('a1_tienda', 'A1',
       {'es': 'En la tienda', 'ru': 'В магазине', 'uk': 'У магазині', 'ar': 'في المتجر', 'fr': 'Au magasin', 'en': 'At the shop'},
       'dependiente de una tienda de alimentación',
       {'es': 'Comprar fruta y pan', 'ru': 'Купить фрукты и хлеб', 'uk': 'Купити фрукти й хліб', 'ar': 'شراء فاكهة وخبز', 'fr': 'Acheter des fruits et du pain', 'en': 'Buy fruit and bread'},
       'El estudiante debe comprar fruta y pan, preguntar el precio y pagar.',
       'Vas a la tienda del barrio a comprar comida.',
       ['¿Tiene manzanas?', 'Quiero una barra de pan.', '¿Cuánto le debo?']),
    _s('a1_direcciones', 'A1',
       {'es': 'Preguntar el camino', 'ru': 'Спросить дорогу', 'uk': 'Запитати дорогу', 'ar': 'السؤال عن الطريق', 'fr': 'Demander son chemin', 'en': 'Ask for directions'},
       'un vecino amable por la calle',
       {'es': 'Llegar a la estación de tren', 'ru': 'Дойти до вокзала', 'uk': 'Дійти до вокзалу', 'ar': 'الوصول إلى محطة القطار', 'fr': 'Aller à la gare', 'en': 'Get to the train station'},
       'El estudiante debe preguntar cómo llegar a la estación y entender la respuesta.',
       'Estás perdido y buscas la estación de tren.',
       ['Perdone, ¿la estación está cerca?', '¿Cómo llego?', '¿Está lejos?']),
    # ---------------- A2 ----------------
    _s('doctor', 'A2',
       {'es': 'Cita médica', 'ru': 'Приём у врача', 'uk': 'Прийом у лікаря', 'ar': 'موعد طبي', 'fr': 'Rendez-vous médical', 'en': 'Doctor appointment'},
       'recepcionista de un centro de salud',
       {'es': 'Conseguir una cita para la próxima semana por la mañana', 'ru': 'Записаться на приём на следующей неделе утром', 'uk': 'Записатися на прийом наступного тижня вранці', 'ar': 'الحصول على موعد الأسبوع القادم صباحًا', 'fr': 'Obtenir un rendez-vous la semaine prochaine le matin', 'en': 'Get an appointment for next week in the morning'},
       'El estudiante debe conseguir una cita médica para la próxima semana por la mañana (día y hora).',
       'Llamas al centro de salud para pedir cita con tu médico de cabecera.',
       ['Buenos días, quería pedir una cita.', '¿Tiene algo para la próxima semana?', 'Por la mañana, si es posible.']),
    _s('a2_restaurante', 'A2',
       {'es': 'Cenar en un restaurante', 'ru': 'Ужин в ресторане', 'uk': 'Вечеря в ресторані', 'ar': 'العشاء في مطعم', 'fr': 'Dîner au restaurant', 'en': 'Dinner at a restaurant'},
       'camarero de un restaurante',
       {'es': 'Pedir un menú completo y la cuenta', 'ru': 'Заказать полный ужин и счёт', 'uk': 'Замовити повну вечерю та рахунок', 'ar': 'طلب وجبة كاملة والفاتورة', 'fr': 'Commander un menu complet et l’addition', 'en': 'Order a full meal and the bill'},
       'El estudiante debe pedir primer plato, segundo, bebida y postre, y luego la cuenta.',
       'Cenas fuera y el camarero te atiende.',
       ['¿Me trae la carta?', 'De primero quiero...', 'La cuenta, por favor.']),
    _s('a2_hotel', 'A2',
       {'es': 'Reservar un hotel', 'ru': 'Бронь отеля', 'uk': 'Бронювання готелю', 'ar': 'حجز فندق', 'fr': 'Réserver un hôtel', 'en': 'Book a hotel'},
       'recepcionista de un hotel',
       {'es': 'Reservar una habitación para dos noches', 'ru': 'Забронировать номер на две ночи', 'uk': 'Забронювати номер на дві ночі', 'ar': 'حجز غرفة لليلتين', 'fr': 'Réserver une chambre pour deux nuits', 'en': 'Book a room for two nights'},
       'El estudiante debe reservar una habitación para dos noches y preguntar por el desayuno.',
       'Llamas a un hotel para reservar.',
       ['Quería reservar una habitación.', 'Para dos noches.', '¿El desayuno está incluido?']),
    _s('a2_farmacia', 'A2',
       {'es': 'En la farmacia', 'ru': 'В аптеке', 'uk': 'В аптеці', 'ar': 'في الصيدلية', 'fr': 'À la pharmacie', 'en': 'At the pharmacy'},
       'farmacéutico',
       {'es': 'Explicar tus síntomas y conseguir algo para el resfriado', 'ru': 'Описать симптомы и получить средство от простуды', 'uk': 'Описати симптоми й отримати ліки від застуди', 'ar': 'شرح الأعراض والحصول على دواء للزكام', 'fr': 'Décrire tes symptômes et obtenir un remède contre le rhume', 'en': 'Describe symptoms and get a cold remedy'},
       'El estudiante debe describir sus síntomas y conseguir un medicamento adecuado.',
       'No te encuentras bien y vas a la farmacia.',
       ['Me duele la garganta.', '¿Qué me recomienda?', '¿Cómo lo tomo?']),
    # ---------------- B1 ----------------
    _s('rental', 'B1',
       {'es': 'Alquilar un piso', 'ru': 'Аренда квартиры', 'uk': 'Оренда квартири', 'ar': 'استئجار شقة', 'fr': 'Louer un appartement', 'en': 'Rent a flat'},
       'propietario que alquila un piso',
       {'es': 'Preguntar por el piso y concertar una visita', 'ru': 'Расспросить о квартире и договориться о просмотре', 'uk': 'Розпитати про квартиру й домовитися про перегляд', 'ar': 'الاستفسار عن الشقة وتحديد موعد للمعاينة', 'fr': 'Se renseigner et convenir d’une visite', 'en': 'Ask about the flat and arrange a viewing'},
       'El estudiante debe preguntar precio, gastos y condiciones, y quedar para verlo.',
       'Llamas por un anuncio de alquiler.',
       ['Llamo por el piso que se alquila.', '¿Los gastos están incluidos?', '¿Puedo verlo esta semana?']),
    _s('city_hall', 'B1',
       {'es': 'Empadronamiento', 'ru': 'Прописка (empadronamiento)', 'uk': 'Реєстрація місця проживання', 'ar': 'التسجيل في البلدية', 'fr': 'Inscription à la mairie', 'en': 'Town-hall registration'},
       'funcionario del ayuntamiento',
       {'es': 'Empadronarte y saber qué documentos necesitas', 'ru': 'Прописаться и узнать нужные документы', 'uk': 'Зареєструватися й дізнатися потрібні документи', 'ar': 'التسجيل ومعرفة الوثائق المطلوبة', 'fr': 'T’inscrire et connaître les documents requis', 'en': 'Register and learn which documents you need'},
       'El estudiante debe pedir cita/empadronarse y averiguar los documentos necesarios.',
       'Vas al ayuntamiento para empadronarte.',
       ['Vengo a empadronarme.', '¿Qué documentos necesito?', '¿Tengo que pedir cita?']),
    _s('b1_devolucion', 'B1',
       {'es': 'Devolver un producto', 'ru': 'Вернуть товар', 'uk': 'Повернути товар', 'ar': 'إرجاع منتج', 'fr': 'Rendre un produit', 'en': 'Return an item'},
       'dependiente de una tienda de electrónica',
       {'es': 'Devolver un aparato defectuoso y recuperar el dinero', 'ru': 'Вернуть бракованный прибор и получить деньги', 'uk': 'Повернути браковану річ і отримати гроші', 'ar': 'إرجاع جهاز معيب واسترداد المال', 'fr': 'Rendre un appareil défectueux et être remboursé', 'en': 'Return a faulty device and get a refund'},
       'El estudiante debe explicar el problema y conseguir un reembolso o cambio.',
       'Compraste un aparato que no funciona y vuelves a la tienda.',
       ['Este aparato no funciona.', 'Quisiera que me devuelvan el dinero.', 'Aquí está el ticket.']),
    _s('b1_primer_dia', 'B1',
       {'es': 'Primer día de trabajo', 'ru': 'Первый день на работе', 'uk': 'Перший день на роботі', 'ar': 'أول يوم عمل', 'fr': 'Premier jour de travail', 'en': 'First day at work'},
       'un compañero de trabajo que te enseña la oficina',
       {'es': 'Presentarte y entender tus tareas del día', 'ru': 'Представиться и понять свои задачи на день', 'uk': 'Представитися й зрозуміти завдання на день', 'ar': 'التعريف بنفسك وفهم مهامك اليومية', 'fr': 'Te présenter et comprendre tes tâches du jour', 'en': 'Introduce yourself and understand your tasks'},
       'El estudiante debe presentarse, preguntar por sus tareas y por dónde está todo.',
       'Es tu primer día y un compañero te recibe.',
       ['Encantado, soy el nuevo.', '¿Qué tengo que hacer hoy?', '¿Dónde está la sala de reuniones?']),
    # ---------------- B2 ----------------
    _s('bank', 'B2',
       {'es': 'Reclamar en el banco', 'ru': 'Спор в банке', 'uk': 'Суперечка в банку', 'ar': 'شكوى في البنك', 'fr': 'Réclamation à la banque', 'en': 'Bank complaint'},
       'empleado de atención al cliente de un banco',
       {'es': 'Reclamar una comisión cobrada por error y pedir su devolución', 'ru': 'Оспорить ошибочную комиссию и добиться возврата', 'uk': 'Оскаржити помилкову комісію та домогтися повернення', 'ar': 'الاعتراض على رسوم بالخطأ وطلب استردادها', 'fr': 'Contester des frais prélevés par erreur et demander un remboursement', 'en': 'Dispute a wrongly charged fee and get it refunded'},
       'El estudiante debe explicar el problema y conseguir que el banco acepte devolver la comisión.',
       'Vas al banco porque te han cobrado una comisión que no reconoces.',
       ['Me han cobrado una comisión que no reconozco.', '¿Podrían revisarlo?', 'Me gustaría que me la devolvieran.']),
    _s('interview', 'B2',
       {'es': 'Entrevista de trabajo', 'ru': 'Собеседование', 'uk': 'Співбесіда', 'ar': 'مقابلة عمل', 'fr': "Entretien d'embauche", 'en': 'Job interview'},
       'responsable de recursos humanos',
       {'es': 'Presentarte y explicar por qué eres buen candidato', 'ru': 'Представить себя и объяснить, почему вы хороший кандидат', 'uk': 'Представити себе і пояснити, чому ви хороший кандидат', 'ar': 'التعريف بنفسك وشرح لماذا أنت مرشح مناسب', 'fr': 'Te présenter et expliquer pourquoi tu es un bon candidat', 'en': 'Introduce yourself and explain why you are a good candidate'},
       'El estudiante debe presentarse, hablar de su experiencia y dar al menos dos razones para ser contratado.',
       'Tienes una entrevista para un puesto que te interesa.',
       ['Tengo experiencia en...', 'Mis puntos fuertes son...', 'Me interesa este puesto porque...']),
    _s('b2_reclamacion', 'B2',
       {'es': 'Reclamación de un pedido', 'ru': 'Претензия по заказу', 'uk': 'Претензія щодо замовлення', 'ar': 'شكوى بشأن طلب', 'fr': 'Réclamation d’une commande', 'en': 'Complaint about an order'},
       'atención al cliente de una tienda online',
       {'es': 'Reclamar un pedido que llegó dañado y exigir una solución', 'ru': 'Оспорить повреждённый заказ и потребовать решения', 'uk': 'Оскаржити пошкоджене замовлення й вимагати рішення', 'ar': 'الشكوى من طلب وصل تالفًا وطلب حل', 'fr': 'Réclamer une commande arrivée abîmée et exiger une solution', 'en': 'Complain about a damaged order and demand a fix'},
       'El estudiante debe explicar el problema con firmeza y conseguir reemplazo o reembolso.',
       'Tu pedido llegó roto y contactas con la tienda.',
       ['Mi pedido llegó dañado.', 'Esto es inaceptable.', 'Exijo un reemplazo o el reembolso.']),
    _s('b2_negociar', 'B2',
       {'es': 'Negociar el precio', 'ru': 'Торг о цене', 'uk': 'Торг про ціну', 'ar': 'التفاوض على السعر', 'fr': 'Négocier le prix', 'en': 'Negotiate the price'},
       'vendedor en un mercadillo de segunda mano',
       {'es': 'Conseguir una rebaja razonable del precio', 'ru': 'Добиться разумной скидки', 'uk': 'Домогтися розумної знижки', 'ar': 'الحصول على خصم معقول', 'fr': 'Obtenir une remise raisonnable', 'en': 'Get a reasonable discount'},
       'El estudiante debe regatear y conseguir un precio más bajo con argumentos.',
       'Ves un objeto que te gusta pero es caro.',
       ['¿Es lo mejor que me puede hacer?', 'Le doy la mitad.', '¿Quedamos en un punto medio?']),
    # ---------------- C1 ----------------
    _s('c1_debate', 'C1',
       {'es': 'Debate sobre el teletrabajo', 'ru': 'Спор об удалёнке', 'uk': 'Дискусія про віддалену роботу', 'ar': 'نقاش حول العمل عن بُعد', 'fr': 'Débat sur le télétravail', 'en': 'Debate on remote work'},
       'un colega con una opinión contraria a la tuya',
       {'es': 'Defender tu postura con argumentos y matices', 'ru': 'Отстоять свою позицию с аргументами и нюансами', 'uk': 'Відстояти позицію з аргументами й нюансами', 'ar': 'الدفاع عن رأيك بحجج ودقائق', 'fr': 'Défendre ta position avec des arguments nuancés', 'en': 'Defend your view with nuanced arguments'},
       'El estudiante debe argumentar su postura, rebatir objeciones y matizar.',
       'En una reunión surge un debate sobre el teletrabajo.',
       ['Sostengo que...', 'Reconozco tu punto, pero...', 'Depende de cómo se gestione.']),
    _s('c1_queja_formal', 'C1',
       {'es': 'Queja formal en un hotel', 'ru': 'Официальная жалоба в отеле', 'uk': 'Офіційна скарга в готелі', 'ar': 'شكوى رسمية في فندق', 'fr': 'Réclamation formelle à l’hôtel', 'en': 'Formal hotel complaint'},
       'gerente de un hotel',
       {'es': 'Exponer una queja formal y obtener una compensación', 'ru': 'Изложить официальную жалобу и получить компенсацию', 'uk': 'Викласти офіційну скаргу й отримати компенсацію', 'ar': 'تقديم شكوى رسمية والحصول على تعويض', 'fr': 'Exposer une réclamation formelle et obtenir une compensation', 'en': 'State a formal complaint and get compensation'},
       'El estudiante debe exponer la queja con registro formal y negociar una compensación.',
       'El servicio del hotel ha sido deficiente y hablas con el gerente.',
       ['Quisiera dejar constancia de mi descontento.', 'Se me prometió algo que no se cumplió.', 'Espero una compensación adecuada.']),
    _s('c1_prestamo', 'C1',
       {'es': 'Condiciones de un préstamo', 'ru': 'Условия кредита', 'uk': 'Умови кредиту', 'ar': 'شروط قرض', 'fr': 'Conditions d’un prêt', 'en': 'Loan conditions'},
       'asesor bancario',
       {'es': 'Entender las condiciones y decidir con criterio', 'ru': 'Понять условия и принять взвешенное решение', 'uk': 'Зрозуміти умови й ухвалити зважене рішення', 'ar': 'فهم الشروط واتخاذ قرار مدروس', 'fr': 'Comprendre les conditions et décider en connaissance de cause', 'en': 'Understand the terms and decide wisely'},
       'El estudiante debe preguntar por intereses, plazos y comisiones, y valorar la oferta.',
       'Vas al banco para informarte sobre un préstamo.',
       ['¿Cuál es el tipo de interés?', '¿Hay comisiones de apertura?', 'Me lo pensaré, gracias.']),
    _s('c1_reunion', 'C1',
       {'es': 'Repartir tareas del proyecto', 'ru': 'Распределение задач проекта', 'uk': 'Розподіл завдань проєкту', 'ar': 'توزيع مهام المشروع', 'fr': 'Répartir les tâches du projet', 'en': 'Split project tasks'},
       'un compañero en una reunión de trabajo',
       {'es': 'Acordar un reparto de tareas y plazos', 'ru': 'Согласовать распределение задач и сроки', 'uk': 'Узгодити розподіл завдань і терміни', 'ar': 'الاتفاق على توزيع المهام والمواعيد', 'fr': 'Convenir d’une répartition des tâches et des délais', 'en': 'Agree on task allocation and deadlines'},
       'El estudiante debe proponer, negociar y cerrar un reparto de tareas con plazos.',
       'Tu equipo debe organizar un proyecto con un plazo ajustado.',
       ['Propongo que yo me encargue de...', '¿Podrías ocuparte tú de...?', 'Entonces, ¿lo cerramos así?']),
    # ---------------- C2 ----------------
    _s('c2_negociacion', 'C2',
       {'es': 'Negociación comercial', 'ru': 'Коммерческие переговоры', 'uk': 'Комерційні перемовини', 'ar': 'تفاوض تجاري', 'fr': 'Négociation commerciale', 'en': 'Business negotiation'},
       'un socio comercial que defiende los intereses de su empresa',
       {'es': 'Cerrar un acuerdo favorable con contrapartidas', 'ru': 'Заключить выгодное соглашение с уступками', 'uk': 'Укласти вигідну угоду з поступками', 'ar': 'إبرام اتفاق مؤاتٍ مع مقابل', 'fr': 'Conclure un accord favorable avec contreparties', 'en': 'Close a favourable deal with trade-offs'},
       'El estudiante debe negociar con matices, proponer contrapartidas y cerrar un acuerdo.',
       'Negocias un contrato con un socio exigente.',
       ['No lo rechazamos, lo matizaríamos.', 'A cambio, necesitaríamos...', 'Si se respetan los plazos, aceptamos.']),
    _s('c2_mediacion', 'C2',
       {'es': 'Mediar en un conflicto', 'ru': 'Медиация конфликта', 'uk': 'Медіація конфлікту', 'ar': 'الوساطة في نزاع', 'fr': 'Médiation de conflit', 'en': 'Mediate a conflict'},
       'la otra parte de un conflicto vecinal',
       {'es': 'Exponer tu postura y alcanzar un acuerdo sin romper la relación', 'ru': 'Изложить позицию и достичь соглашения, не разрушив отношения', 'uk': 'Викласти позицію й дійти згоди, не зіпсувавши стосунки', 'ar': 'عرض موقفك والوصول إلى اتفاق دون قطع العلاقة', 'fr': 'Exposer ta position et trouver un accord sans rompre la relation', 'en': 'State your position and reach a deal without breaking the relationship'},
       'El estudiante debe defender sus intereses con tacto y buscar un punto de encuentro.',
       'Hay un desacuerdo con un vecino y buscáis una solución.',
       ['Entiendo tu punto de vista, pero...', 'Busquemos una solución para ambos.', '¿Te parece razonable si...?']),
    _s('c2_entrevista_experto', 'C2',
       {'es': 'Entrevista como experto', 'ru': 'Интервью как эксперт', 'uk': 'Інтервʼю як експерт', 'ar': 'مقابلة كخبير', 'fr': 'Interview en tant qu’expert', 'en': 'Interview as an expert'},
       'un periodista que te hace preguntas incisivas',
       {'es': 'Responder con solvencia y matizar tus afirmaciones', 'ru': 'Отвечать уверенно и уточнять свои утверждения', 'uk': 'Відповідати впевнено й уточнювати твердження', 'ar': 'الإجابة باقتدار وتوضيح تصريحاتك', 'fr': 'Répondre avec assurance et nuancer tes propos', 'en': 'Answer competently and qualify your claims'},
       'El estudiante debe responder preguntas difíciles con precisión y matices.',
       'Te entrevistan como experto en tu campo.',
       ['Conviene matizar que...', 'La evidencia sugiere que...', 'No es tan sencillo, y le explico por qué.']),
    _s('c2_academico', 'C2',
       {'es': 'Debate académico', 'ru': 'Академический спор', 'uk': 'Академічна дискусія', 'ar': 'نقاش أكاديمي', 'fr': 'Débat académique', 'en': 'Academic debate'},
       'un profesor universitario que cuestiona tus ideas',
       {'es': 'Sostener una tesis abstracta ante objeciones', 'ru': 'Отстоять абстрактный тезис перед возражениями', 'uk': 'Відстояти абстрактну тезу перед запереченнями', 'ar': 'الدفاع عن أطروحة مجردة أمام الاعتراضات', 'fr': 'Soutenir une thèse abstraite face aux objections', 'en': 'Defend an abstract thesis against objections'},
       'El estudiante debe argumentar una tesis abstracta, responder objeciones y concluir.',
       'Discutes con un profesor sobre libertad y tecnología.',
       ['Mi tesis es que...', 'Cabría objetar que..., y sin embargo...', 'En conclusión, sostengo que...']),
]

_BY_ID = {s['id']: s for s in SCENARIOS}
_BY_LEVEL: dict[str, list[dict]] = {}
for _s2 in SCENARIOS:
    _BY_LEVEL.setdefault(_s2['level'], []).append(_s2)


def public_list(native_language: str, level: str | None = None) -> list[dict]:
    lang = (native_language or 'ru')[:2]
    items = _BY_LEVEL.get((level or '').upper(), []) if level else SCENARIOS
    out = []
    for s in items:
        out.append({
            'id': s['id'], 'level': s['level'],
            'title': s['title'].get(lang, s['title']['en']),
            'role': s['role'],
            'goal': s['goal'].get(lang, s['goal']['en']),
            'setup': s['setup_es'],
            'hints': s['hints'],
        })
    return out


def get(scenario_id: str) -> dict | None:
    return _BY_ID.get(scenario_id)
